package cn.itcast.dao.cargo;

import cn.itcast.domain.cargo.CoPackingList;
import cn.itcast.domain.cargo.CoPackingListExample;

import java.util.List;

public interface CoPackingListDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_packing_list
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String packingListId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_packing_list
     *
     * @mbg.generated
     */
    int insert(CoPackingList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_packing_list
     *
     * @mbg.generated
     */
    int insertSelective(CoPackingList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_packing_list
     *
     * @mbg.generated
     */
    List<CoPackingList> selectByExample(CoPackingListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_packing_list
     *
     * @mbg.generated
     */
    CoPackingList selectByPrimaryKey(String packingListId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_packing_list
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CoPackingList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_packing_list
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CoPackingList record);
}